[project]
authors = [{ name = "Yuncong Yu", email = "yuncong.yu@outlook.com" }]
dependencies = []
name = "data-science"
requires-python = ">= 3.11"
version = "0.1.0"
keywords = ["data science", "machine learning", "artificial intelligence", "statistics", "visual analytics"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
data_science = { path = ".", editable = true }

[tool.pixi.tasks]
ci = { depends-on = ["lint", "test"]}

[tool.pixi.dependencies]
cuda = ">=13.1.1,<14"
ipykernel = ">=7.1.0,<8"
jupyter = ">=1.1.1,<2"
matplotlib = ">=3.10.8,<4"
numpy = ">=2.4.1,<3"
pandas = ">=3.0.0,<4"
python = ">=3.12.12,<3.13"
scikit-learn = ">=1.8.0,<2"
streamlit = ">=1.9.0,<2"
tensorflow = ">=2.19.1,<3"

[tool.pixi.feature.lint.dependencies]
ruff = "*"
mypy = "*"
pre-commit = "*"
pandas-stubs = ">=3.0.0.260204,<4"
types-tqdm = ">=4.67.3.20260205,<5"

[tool.pixi.feature.lint.tasks]
ruff = "ruff"
check = "ruff check ."
format = "ruff format ."
format-check = "ruff format --check ."
type-check = "mypy ."

[tool.pixi.feature.test.dependencies]
pytest = "*"
pytest-cov = ">=7.0.0,<8"

[tool.pixi.feature.test.tasks]
test = "pytest"

[tool.pixi.environments]
dev = ["lint", "test"]

[tool.ruff]
line-length = 88
extend-exclude = [
    "experiments/homl/ch02*.ipynb", 
    "experiments/homl/ch03*.ipynb", 
    "experiments/homl/ch04*.ipynb",
    "experiments/homl/ch05*.ipynb",
    "experiments/homl/ch06*.ipynb",
    "experiments/homl/ch07*.ipynb",
    "experiments/homl/ch08*.ipynb",
    "experiments/homl/ch09*.ipynb",
    "experiments/homl/ch10*.ipynb",
]

[tool.mypy]
strict = true
ignore_missing_imports = true
exclude = [""]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

